# Generated by Django 3.1.12 on 2025-07-21 16:29

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20250721_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=store.models.upload_to),
        ),
    ]
