# Generated by Django 3.1.12 on 2025-08-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20250728_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15)),
                ('user_address', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_contact', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=15)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_description', models.TextField()),
                ('product_category', models.CharField(max_length=50)),
                ('product_quantity', models.IntegerField()),
            ],
        ),
    ]
