# Generated by Django 3.1.12 on 2025-08-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_amount',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='store_purchase',
        ),
    ]
